---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[mysql-mha::default]
    attributes:
